### ISSUE TITLE
Log Level Questions

### ISSUE THREAD

**Issue by Rcvisual** [xuperchain/xuperunion#100] opened 2019-06-18 03:52 UTC
**Brief of the issue**
日志级别疑问,"github.com\xuperchain\log15\logger.go"文件中日志级别为:
const (
	LvlCrit Lvl = iota
	LvlError
	LvlWarn
	LvlInfo
	LvlTrace
	LvlDebug
)
也就是说,crit<err<warn<info<trace<debug,但在文档中5.2 配置文件说明
level : trace // 日志等级，debug < trace < info < warn < error < crit,而且阅读日志源码也有此疑问,是为了便于理解的改变?

**Repo steps**
https://github.com/xuperchain/log15/blob/master/logger.go 19
common/log/log.go 57 60
**Expected behaviours**
common/log/log.go 57 60
// prints log level between `lvLevel` to Info to common log
nmfileh := log.BoundLvlFilterHandler(lvLevel, log.LvlError, nmHandler)

**What actually happened**
按照注释的修改
// prints log level between `lvLevel` to Info to common log
nmfileh := log.BoundLvlFilterHandler(lvLevel,LvlInfo,nmHandler)

**Comment by yucaowang** [comment] 2019-06-18 05:42
Yes, we want to print all log info into xchain.log and only print warn/error/crit log into xchain.log.wf, this could help to analyse log context in one file.
So in this case, the comment is out-of-date.

**Comment by Rcvisual** [comment] 2019-06-18 05:47
> Yes, we want to print all log info into xchain.log and only print warn/error/crit log into xchain.log.wf, this could help to analyse log context in one file.
> So in this case, the comment is out-of-date.

OK

**Comment by yucaowang** [comment] 2019-06-18 05:59
@Rcvisual thanks for the issue, we will update our comment later. I will close this issue at this time since it's not a bug.

**Closed by yucaowang** 2019-06-18 05:59 UTC
