### ISSUE TITLE
The nomination of tdpos that candidate mismatches neturl can succeed

### ISSUE THREAD

**Issue by wenjingLi729** [xuperchain/xuperunion#250] opened 2019-07-30 11:44 UTC
**Brief of the issue**
The nomination of tdpos that candidate mismatches neturl can succeed

**Your environment**
XuperUnion and OS/Go/gcc version etc.

**Repo steps**
setp1
Nominate.json that candidate mismatches neturl
step2
./xchain-cli multisig gen --to=$addr --desc=./nominate.json --multiAddrs=./data/acl/addrs --amount=$amount --frozen=-1
sign tx.out
send tx.out
step3
The nomination was successful.
step4
Vote the candidate and then find the vote successfully.

**Expected behaviours**
Describe what you expected to happen.

**What actually happened**

**Additional information**
If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

**Comment by yucaowang** [comment] 2019-07-31 02:25
Seems by design.

1. Nominating candidate should include the signature of the candidate, so it's the candidate's responsible to check the netURL.
2. Other nodes cannot know the information of the candidate. For example, we can nominate a node that when it's still offline. It's just the same with the candidate's address, we have no responsibility and hardly to check whether the address is valid.
3. If the candidate info is changed after nomination, user can revoke the nomination and nominate with correct info again.

**Comment by ToWorld** [comment] 2019-08-28 10:15
Closing this.

**Closed by ToWorld** 2019-08-28 10:15 UTC
